### ISSUE TITLE
Readme has space in 'Orange Crab"

### ISSUE THREAD

**Issue by CarlFK** [gregdavill/OrangeCrab#13]
I care because I am writing up promo material.

I'm assuming no space because this has no space:

https://github.com/gregdavill/OrangeCrab/blob/master/documentation/hugo-files/content/r0.1/_index.md

**Comment by gregdavill** [comment]
Thanks Carl. Yep that should be changed to not have a space, just to remain consistent.

Everywhere else I've not used a space, and kept it one word.

**Comment by gregdavill** [comment]
Fixed in: https://github.com/gregdavill/OrangeCrab/commit/76b73c0cee7ae94dbd78d5746ec94f7d27d54ec4
